# Starship configurations
# https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\

  $kubernetes\
  $nodejs\
  $rust\

  $jobs\
  $cmd_duration\
  $status\
  $shlvl\
  $line_break\

  $character\
  """
scan_timeout = 10

[cmd_duration]
disabled = false
min_time = 1000
show_milliseconds = true

[directory]
disabled = false
truncation_length = 5
truncate_to_repo = true

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[jobs]
disabled = false

[line_break]
disabled = false

[kubernetes]
disabled = false

[nodejs]
disabled = false
detect_files = ["package.json"]

[rust]
disabled = false
detect_extensions = []

[username]
disabled = false
show_always = false

[shlvl]
disabled = false
format = "[/lv:$shlvl/]($style)"
style = "bold blue"

[status]
disabled = false

## Unused modules
[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[python]
disabled = true
detect_extensions = []
